<?php
	echo '
		<script>
				var BROWSER_AJAX = "'.BROWSER_AJAX.'";
				var BROWSER_AJAX_CART = "'.BROWSER_AJAX_CART.'";
				var BROWSER_ADMIN = "'.BROWSER_ADMIN.'";
				var BROWSER_IMAGES = "'.BROWSER_IMAGES.'";
				var BROWSER_FONTS = "'.BROWSER_FONTS.'";
				var BROWSER_PORTFOLIOS = "'.BROWSER_PORTFOLIOS.'";
				var BROWSER_PRODUCTS = "'.BROWSER_PRODUCTS.'";
				var BROWSER_LIB = "'.BROWSER_LIB.'";
				var BROWSER_ENVELOPES = "'.BROWSER_ENVELOPES.'";
				var BROWSER_INDEX = "'.BROWSER_INDEX.'";
				var BROWSER_THEME_IMAGES = "'.BROWSER_THEME_IMAGES.'";
				
				var SERVER_ADMIN_ROOT = "'.SERVER_ADMIN_ROOT.'";				
				
				var AJAX_STATUS_FAIL = '.AJAX_STATUS_FAIL.';
				var AJAX_STATUS_OK = '.AJAX_STATUS_OK.';
				
				var AJAX_STATUS_FAIL_EMPTY_CART = '.AJAX_STATUS_FAIL_EMPTY_CART.';
				var AJAX_STATUS_FAIL_SESSION = '.AJAX_STATUS_FAIL_SESSION.';
				var AJAX_STATUS_FAIL_TRANSACTION = '.AJAX_STATUS_FAIL_TRANSACTION.';
				var AJAX_STATUS_FAIL_CUSTOMER = '.AJAX_STATUS_FAIL_CUSTOMER.';
				var AJAX_STATUS_FAIL_ORDER = '.AJAX_STATUS_FAIL_ORDER.';
				var AJAX_STATUS_FAIL_ITEM_MISSING = '.AJAX_STATUS_FAIL_ITEM_MISSING.';
				var AJAX_STATUS_FAIL_ITEM_PRICE = '.AJAX_STATUS_FAIL_ITEM_PRICE.';
				var AJAX_STATUS_FAIL_ITEM = '.AJAX_STATUS_FAIL_ITEM.';
				var AJAX_STATUS_FAIL_CC = '.AJAX_STATUS_FAIL_CC.';
				
				var BORDER_NONE = '.BORDER_NONE.';
				var BORDER_DOTTED = '.BORDER_DOTTED.';
				var BORDER_SOLID = '.BORDER_SOLID.';
				var BORDER_ROUNDED = '.BORDER_ROUNDED.';
				var BORDER_STRIPED = '.BORDER_STRIPED.';
				var BORDER_MATTE = '.BORDER_MATTE.';
				
				var RETURN_ADDRESS_COST = '.RETURN_ADDRESS_COST.';
				var SHIPPING_COST = '.SHIPPING_COST.';
				
				var MD_STATE_ID = '.MD_STATE_ID.';
				var VA_STATE_ID = '.VA_STATE_ID.';
				var MD_TAX = '.MD_TAX.';
				var VA_TAX = '.VA_TAX.';
		</script>';	
?>